matcher:
  KDTreeMatcher:
    knn: 8
    maxDist: 1
    epsilon: 1

outlierFilters:
  - TrimmedDistOutlierFilter:
      ratio: 0.5

errorMinimizer:
  PointToPlaneErrorMinimizer:

transformationCheckers:
  - DifferentialTransformationChecker:
      minDiffRotErr: 0.001
      minDiffTransErr: 0.01
      smoothLength: 2
  - CounterTransformationChecker:
      maxIterationCount: 40
  - BoundTransformationChecker:
      maxRotationNorm: 1.1
      maxTranslationNorm: 15.0

inspector:
  NullInspector

logger:
  NullLogger
